import React from "react"
import { View, Image, ImageBackground, Button, Text } from "react-native"
import {
  withStyles,
  Text,
  Button,
  CheckBox,
  Radio,
  Toggle,
  Icon,
  Input,
  Datepicker
} from "react-native-ui-kitten"
import Slider from "@react-native-community/slider"

import { SlideMenuIcon } from "../../../navigator/slideMenuIcon"

export class _Blank extends React.Component {
  static navigationOptions = ({ navigation }) => {
    return {
      headerLeft: <SlideMenuIcon navigationProps={navigation} />
    }
  }

  state = {}

  render = () => (
    <View
      style={{
        width: '100%',
        height: '100%',
        marginLeft: 0,
        marginRight: 0,
        marginTop: 0,
        marginBottom: 0,
        paddingLeft: 0,
        paddingRight: 0,
        paddingTop: 0,
        paddingBottom: 0,
        overflow: 'visible',
        textAlign: 'left',
        verticalAlign: 'baseline',
        fontSize: 20,
        color: '#000000',
        backgroundColor: '#f4f5f9',
        fontFamily: 'Roboto-Regular',
        flexDirection: 'column',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        alignContent: 'stretch',
        borderColor: '#000000',
        borderStyle: 'solid',
        borderWidth: 0,
        borderLeftWidth: 0,
        borderRightWidth: 0,
        borderTopWidth: 0,
        borderBottomWidth: 0,
        borderRadius: 0,
        backgroundSize: 'auto',
      }}>
      <View
        style={{
          width: '100%',
          height: '80%',
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
          overflow: 'visible',
          textAlign: 'left',
          verticalAlign: 'baseline',
          fontSize: 20,
          color: '#000000',
          backgroundColor: '#f4f5f9',
          fontFamily: 'Roboto-Regular',
          flexDirection: 'column',
          flexWrap: 'wrap',
          justifyContent: 'flex-start',
          alignItems: 'stretch',
          alignContent: 'stretch',
          borderColor: '#000000',
          borderStyle: 'solid',
          borderWidth: 0,
          borderLeftWidth: 0,
          borderRightWidth: 0,
          borderTopWidth: 0,
          borderBottomWidth: 0,
          borderRadius: 0,
          backgroundSize: 'auto',
        }}>
        <View
          style={{
            width: '100%',
            height: '15%',
            marginLeft: 0,
            marginRight: 0,
            marginTop: 0,
            marginBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            overflow: 'visible',
            textAlign: 'left',
            verticalAlign: 'baseline',
            fontSize: 20,
            color: '#000000',
            backgroundColor: '#f4f5f9',
            fontFamily: 'Roboto-Regular',
            flexDirection: 'column',
            flexWrap: 'wrap',
            justifyContent: 'flex-start',
            alignItems: 'stretch',
            alignContent: 'stretch',
            borderColor: '#000000',
            borderStyle: 'solid',
            borderWidth: 0,
            borderLeftWidth: 0,
            borderRightWidth: 0,
            borderTopWidth: 0,
            borderBottomWidth: 0,
            borderRadius: 0,
            backgroundSize: 'auto',
          }}>
          <View
            style={{
              width: '100%',
              height: '50%',
              marginLeft: 0,
              marginRight: 0,
              marginTop: 0,
              marginBottom: 0,
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              overflow: 'visible',
              textAlign: 'left',
              verticalAlign: 'baseline',
              fontSize: 20,
              color: '#000000',
              backgroundColor: '#f4f5f9',
              fontFamily: 'Roboto-Regular',
              flexDirection: 'row',
              flexWrap: 'wrap',
              justifyContent: 'flex-start',
              alignItems: 'stretch',
              alignContent: 'stretch',
              borderColor: '#000000',
              borderStyle: 'solid',
              borderWidth: 0,
              borderLeftWidth: 0,
              borderRightWidth: 0,
              borderTopWidth: 0,
              borderBottomWidth: 0,
              borderRadius: 0,
              backgroundSize: 'auto',
            }}>
            <View
              style={{
                width: '15%',
                height: '100%',
                marginLeft: 0,
                marginRight: 0,
                marginTop: 0,
                marginBottom: 0,
                paddingLeft: 0,
                paddingRight: 0,
                paddingTop: 0,
                paddingBottom: 0,
                overflow: 'visible',
                textAlign: 'left',
                verticalAlign: 'baseline',
                fontSize: 20,
                color: '#000000',
                backgroundColor: '#fd6f80',
                fontFamily: 'Roboto-Regular',
                flexDirection: 'column',
                flexWrap: 'wrap',
                justifyContent: 'flex-start',
                alignItems: 'stretch',
                alignContent: 'stretch',
                borderColor: '#000000',
                borderStyle: 'solid',
                borderWidth: 0,
                borderLeftWidth: 0,
                borderRightWidth: 0,
                borderTopWidth: 0,
                borderBottomWidth: 0,
                borderRadius: 0,
                backgroundSize: 'auto',
              }}>
              <Button
                style={{
                  width: '90%',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 25,
                  marginBottom: 5,
                  paddingLeft: 5,
                  paddingRight: 5,
                  paddingTop: 5,
                  paddingBottom: 5,
                  overflow: 'visible',
                  textAlign: 'center',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#ffffff',
                  backgroundColor: '#fd6f80',
                  fontFamily: 'Helvetica-Regular',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 0,
                }}
                onPress={() => alert('Pressed!')}
                title = "Back"
                >
                Back
              </Button>
            </View>
            <View
              style={{
                width: '85%',
                height: '100%',
                marginLeft: 0,
                marginRight: 0,
                marginTop: 0,
                marginBottom: 0,
                paddingLeft: 0,
                paddingRight: 0,
                paddingTop: 0,
                paddingBottom: 0,
                overflow: 'visible',
                textAlign: 'left',
                verticalAlign: 'baseline',
                fontSize: 20,
                color: '#000000',
                backgroundColor: '#fd6f80',
                fontFamily: 'Roboto-Regular',
                flexDirection: 'column',
                flexWrap: 'wrap',
                justifyContent: 'flex-start',
                alignItems: 'stretch',
                alignContent: 'stretch',
                borderColor: '#000000',
                borderStyle: 'solid',
                borderWidth: 0,
                borderLeftWidth: 0,
                borderRightWidth: 0,
                borderTopWidth: 0,
                borderBottomWidth: 0,
                borderRadius: 0,
                backgroundSize: 'auto',
              }}>
              <Text
                style={{
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 0,
                  marginBottom: 0,
                  paddingLeft: 5,
                  paddingRight: 5,
                  paddingTop: 5,
                  paddingBottom: 5,
                  overflow: 'visible',
                  textAlign: 'center',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#ffffff',
                  backgroundColor: '#fd6f80',
                  fontFamily: 'Helvetica-Regular',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 0,
                }}>
                Confirmation
              </Text>
            </View>
          </View>
        </View>
        <View
          style={{
            width: '80%',
            height: '70%',
            marginLeft: '10%',
            marginRight: '10%',
            marginTop: 0,
            marginBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            overflow: 'visible',
            textAlign: 'left',
            verticalAlign: 'baseline',
            fontSize: 20,
            color: '#000000',
            backgroundColor: '#ffffff',
            fontFamily: 'Roboto-Regular',
            flexDirection: 'column',
            flexWrap: 'wrap',
            justifyContent: 'flex-start',
            alignItems: 'stretch',
            alignContent: 'stretch',
            borderColor: '#000000',
            borderStyle: 'solid',
            borderWidth: 0,
            borderLeftWidth: 0,
            borderRightWidth: 0,
            borderTopWidth: 0,
            borderBottomWidth: 0,
            borderRadius: 15,
            backgroundSize: 'auto',
          }}>
          <View
            style={{
              width: '80%',
              height: '40%',
              marginLeft: '10%',
              marginRight: '10%',
              marginTop: '10%',
              marginBottom: '10%',
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              overflow: 'visible',
              textAlign: 'left',
              verticalAlign: 'baseline',
              fontSize: 20,
              color: '#000000',
              //backgroundColor: '#ffffff',
              fontFamily: 'Roboto-Regular',
              flexDirection: 'column',
              flexWrap: 'wrap',
              justifyContent: 'flex-start',
              alignItems: 'stretch',
              alignContent: 'stretch',
              borderColor: '#000000',
              borderStyle: 'solid',
              borderWidth: 0,
              borderLeftWidth: 0,
              borderRightWidth: 0,
              borderTopWidth: 0,
              borderBottomWidth: 0,
              borderRadius: 15,
              backgroundSize: 'auto',
            }}>
            <View
              style={{
                width: '100%',
                height: '100%',
                marginLeft: 0,
                marginRight: 0,
                marginTop: 0,
                marginBottom: 0,
                paddingLeft: 0,
                paddingRight: 0,
                paddingTop: 0,
                paddingBottom: 0,
                overflow: 'visible',
                textAlign: 'left',
                verticalAlign: 'baseline',
                fontSize: 20,
                color: '#000000',
                //backgroundColor: '#ffffff',
                fontFamily: 'Roboto-Regular',
                flexDirection: 'column',
                flexWrap: 'wrap',
                justifyContent: 'flex-start',
                alignItems: 'stretch',
                alignContent: 'stretch',
                borderColor: '#000000',
                borderStyle: 'solid',
                borderWidth: 0,
                borderLeftWidth: 0,
                borderRightWidth: 0,
                borderTopWidth: 0,
                borderBottomWidth: 0,
                borderRadius: 0,
                backgroundSize: 'auto',
              }}>
              <View
                style={{
                  width: '100%',
                  height: '0%',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 0,
                  marginBottom: 0,
                  paddingLeft: 0,
                  paddingRight: 0,
                  paddingTop: 0,
                  paddingBottom: 0,
                  overflow: 'visible',
                  textAlign: 'left',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#000000',
                  //backgroundColor: '#ffffff',
                  fontFamily: 'Roboto-Regular',
                  flexDirection: 'column',
                  flexWrap: 'wrap',
                  justifyContent: 'flex-start',
                  alignItems: 'stretch',
                  alignContent: 'stretch',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 0,
                  backgroundSize: 'auto',
                }}
              />
              <View
                style={{
                  width: '100%',
                  height: '30%',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 0,
                  marginBottom: 0,
                  paddingLeft: 0,
                  paddingRight: 0,
                  paddingTop: 0,
                  paddingBottom: 0,
                  overflow: 'visible',
                  textAlign: 'left',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#000000',
                  //backgroundColor: '#ffffff',
                  fontFamily: 'Roboto-Regular',
                  flexDirection: 'column',
                  flexWrap: 'wrap',
                  justifyContent: 'flex-start',
                  alignItems: 'stretch',
                  alignContent: 'stretch',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 14,
                  backgroundSize: 'auto',
                }}>
                <Text
                  style={{
                    marginLeft: 0,
                    marginRight: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    paddingLeft: 5,
                    paddingRight: 5,
                    paddingTop: 5,
                    paddingBottom: 5,
                    overflow: 'visible',
                    textAlign: 'center',
                    verticalAlign: 'baseline',
                    fontSize: 22,
                    color: '#fd6f80',
                    //backgroundColor: '#ffffff',
                    fontFamily: 'Helvetica-Bold',
                    borderColor: '#000000',
                    borderStyle: 'solid',
                    borderWidth: 0,
                    borderLeftWidth: 0,
                    borderRightWidth: 0,
                    borderTopWidth: 0,
                    borderBottomWidth: 0,
                    borderRadius: 14,
                  }}>
                  Payment Confirmed!
                </Text>
              </View>
              <View
                style={{
                  width: '100%',
                  height: '60%',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 0,
                  marginBottom: 0,
                  paddingLeft: 0,
                  paddingRight: 0,
                  paddingTop: 0,
                  paddingBottom: 0,
                  overflow: 'visible',
                  textAlign: 'left',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#000000',
                  //backgroundColor: '#ffffff',
                  fontFamily: 'Roboto-Regular',
                  flexDirection: 'column',
                  flexWrap: 'wrap',
                  justifyContent: 'flex-start',
                  alignItems: 'stretch',
                  alignContent: 'stretch',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 0,
                  backgroundSize: 'auto',
                }}>
                <Text
                  style={{
                    marginLeft: 0,
                    marginRight: 0,
                    marginTop: '7%',
                    marginBottom: '7%',
                    paddingLeft: 0,
                    paddingRight: 0,
                    paddingTop: 0,
                    paddingBottom: 0,
                    overflow: 'visible',
                    textAlign: 'center',
                    verticalAlign: 'baseline',
                    fontSize: 15,
                    color: '#000000',
                    //backgroundColor: '#ffffff',
                    fontFamily: 'Helvetica-Regular',
                    borderColor: '#000000',
                    borderStyle: 'solid',
                    borderWidth: 0,
                    borderLeftWidth: 0,
                    borderRightWidth: 0,
                    borderTopWidth: 0,
                    borderBottomWidth: 0,
                    borderRadius: 0,
                  }}>
                  We&#39;ve sent you an email confirming your order!
                </Text>
              </View>
              <View
                style={{
                  width: '100%',
                  height: '10%',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: 0,
                  marginBottom: 0,
                  paddingLeft: 0,
                  paddingRight: 0,
                  paddingTop: 0,
                  paddingBottom: 0,
                  overflow: 'visible',
                  textAlign: 'left',
                  verticalAlign: 'baseline',
                  fontSize: 20,
                  color: '#000000',
                  backgroundColor: '#ffffff',
                  fontFamily: 'Roboto-Regular',
                  flexDirection: 'column',
                  flexWrap: 'wrap',
                  justifyContent: 'flex-start',
                  alignItems: 'stretch',
                  alignContent: 'stretch',
                  borderColor: '#000000',
                  borderStyle: 'solid',
                  borderWidth: 0,
                  borderLeftWidth: 0,
                  borderRightWidth: 0,
                  borderTopWidth: 0,
                  borderBottomWidth: 0,
                  borderRadius: 0,
                  backgroundSize: 'auto',
                }}>
                <View
                  style={{
                    width: '80%',
                    height: '100%',
                    marginLeft: '10%',
                    marginRight: '10%',
                    marginTop: '10%',
                    marginBottom: '0%',
                    paddingLeft: 0,
                    paddingRight: 0,
                    paddingTop: 0,
                    paddingBottom: 0,
                    overflow: 'visible',
                    textAlign: 'left',
                    verticalAlign: 'baseline',
                    fontSize: 20,
                    color: '#000000',
                    backgroundColor: '#ffffff',
                    fontFamily: 'Roboto-Regular',
                    flexDirection: 'column',
                    flexWrap: 'wrap',
                    justifyContent: 'flex-start',
                    alignItems: 'stretch',
                    alignContent: 'stretch',
                    borderColor: '#000000',
                    borderStyle: 'solid',
                    borderWidth: 0,
                    borderLeftWidth: 0,
                    borderRightWidth: 0,
                    borderTopWidth: 0,
                    borderBottomWidth: 0,
                    borderRadius: 0,
                    backgroundSize: 'auto',
                  }}>
                  <Text
                    style={{
                      marginLeft: 0,
                      marginRight: 0,
                      marginTop: '0%',
                      marginBottom: 0,
                      paddingLeft: 5,
                      paddingRight: 5,
                      paddingTop: 20,
                      paddingBottom: 30,
                      overflow: 'visible',
                      textAlign: 'center',
                      verticalAlign: 'baseline',
                      fontSize: 16,
                      color: '#000000',
                      backgroundColor: '#f4f5f9',
                      fontFamily: 'Helvetica-Regular',
                      borderColor: '#000000',
                      borderStyle: 'solid',
                      borderWidth: 0,
                      borderLeftWidth: 0,
                      borderRightWidth: 0,
                      borderTopWidth: 0,
                      borderBottomWidth: 0,
                      borderRadius: 0,
                    }}>
                    Order #: 918472
                  </Text>
                </View>
              </View>
            </View>
          </View>
        </View>
        <View
          style={{
            width: '100%',
            height: '5%',
            marginLeft: 0,
            marginRight: 0,
            marginTop: '10%',
            marginBottom: 0,
            paddingLeft: 0,
            paddingRight: 0,
            paddingTop: 0,
            paddingBottom: 0,
            overflow: 'visible',
            textAlign: 'left',
            verticalAlign: 'baseline',
            fontSize: 20,
            color: '#000000',
            backgroundColor: '#f4f5f9',
            fontFamily: 'Roboto-Regular',
            flexDirection: 'column',
            flexWrap: 'wrap',
            justifyContent: 'flex-start',
            alignItems: 'stretch',
            alignContent: 'stretch',
            borderColor: '#000000',
            borderStyle: 'solid',
            borderWidth: 0,
            borderLeftWidth: 0,
            borderRightWidth: 0,
            borderTopWidth: 0,
            borderBottomWidth: 0,
            borderRadius: 0,
            backgroundSize: 'auto',
          }}>
          <Button
            style={{
              width: '70%',
              marginLeft: '15%',
              marginRight: '15%',
              marginTop: '10%',
              marginBottom: 5,
              paddingLeft: 5,
              paddingRight: 5,
              paddingTop: 5,
              paddingBottom: 5,
              overflow: 'visible',
              textAlign: 'center',
              verticalAlign: 'baseline',
              fontSize: 23,
              color: '#ffffff',
              backgroundColor: '#fd6f80',
              fontFamily: 'Helvetica-Italic',
              borderColor: '#000000',
              borderStyle: 'solid',
              borderWidth: 0,
              borderLeftWidth: 0,
              borderRightWidth: 0,
              borderTopWidth: 0,
              borderBottomWidth: 0,
              borderRadius: 0,
            }}
            onPress={() => alert('Pressed!')}
            title = 'Return to Profile'
            >
            Return to Profile
          </Button>
        </View>
      </View>
    </View>
  )
}

export default Blank = withStyles(_Blank, theme => ({
  container: {
    backgroundColor: theme["color-basic-100"]
  }
}))
